[project]
name = "Tozo"
version = ""
description = ""
authors = [
    {name = "Phil Jones", email = "pgjones@tozo.dev"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "Private"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
